# -*- coding: utf-8 -*-
print('四則演算')
print('2+2=',2+2)
print('2-2=',2-2)
print('2*2=',2*2)
print('2/2=',2/2)

print('余')
print('3%2=',3%2)
print('商')
print('17//3=',17//3)

print('べき乗')
print('9**0=',9**0)

print('3+(9**3)=',3+(9**3))

# CLIだと前回の計算の答えが_に入るらしい。
# python calc.pyするとちゃんとエラーした。
# 9*9
# _*9
# print(_)